### ISSUE TITLE
fatal error upon activation on my site

### ISSUE THREAD

**Issue by ElisabettaCarrara** [xxsimoxx/cpcompatibility#1]
![Schermata del 2019-07-24 10-46-11](https://user-images.githubusercontent.com/38214395/61783785-bcadf800-ae08-11e9-89ed-8642f7770975.png)

As per image, as soon I installed it it threw such error.
I run the previous version of rankmath (didn't upgrade it before installing the plugin).
Deleted the plugin manually from cPanel, let me know if you need more info about my settings and other plugins I have on site.
Thanks for looking into this

**Comment by xxsimoxx** [comment]
Looks like is_plugin_active is not declared. Moved inside "admin-init". Please try. When downloading, please remove -master from the zip file name.
Thank you!

**Comment by ElisabettaCarrara** [comment]
Works fine now! thanks for looking into this so fast!
