### ISSUE TITLE
Fix CSS path and add context for code

### ISSUE THREAD

**Issue by nylen** [xxsimoxx/cpcompatibility#2]
https://github.com/xxsimoxx/cpcompatibility/blob/e2b26d480ab055e31503f83eb9399880379f1b62/inc/fix-plugins.php#L35

This should be pointing to `css/fake.min.css` instead of `js/fake.min/js`.

https://github.com/xxsimoxx/cpcompatibility/blob/e2b26d480ab055e31503f83eb9399880379f1b62/inc/fix-plugins.php#L24

I would also add some information about the specific problem this is intended to fix, so that it's easier for readers to understand _why_ this code is present. Something like this should do:

> Caldera Forms registers `admin` which depends on `admin-client` which depends on `wp-components`, a Gutenberg script. Other than that it works fine as of version 1.8.5:
> https://forums.classicpress.net/t/problem-with-caldera-forms-and-classicpress/1600

**Comment by xxsimoxx** [comment]
Thank you very much!
